#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TEDRss.Resource", IsApplication=true)]

namespace TEDRss
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050009
			public const int imageView1 = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout2 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout3 = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int linearLayout4 = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int pager = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int relativeLayout1 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int textDate = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int textDescription = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int textDuration = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int textTitle = 2131034116;
			
			// aapt resource value: 0x7f05000b
			public const int videoView1 = 2131034123;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int RssEntry = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Video = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int error_getting_info = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int error_internet_connection = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int getting_info = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int main_activity_title = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int video_activity_title = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
